# Cart Consts
X_CART_LEN = 170
Y_CART_LEN = 240

# Board consts
MOTORS_DIS = 9550


# Motor consts
STEPS_IN_FULL_CIRCLE = 200
BELT_PITCHES_DIS = 2 #in milimeters
PITCHES_IN_CIRCLE = 16
MM_IN_SINGLE_STEP = (PITCHES_IN_CIRCLE * BELT_PITCHES_DIS) / STEPS_IN_FULL_CIRCLE # 16*2/200=0.16
    
